### ISSUE TITLE
Can RedisShake set delay for syncer and schedule to run?

### ISSUE THREAD

**Issue by bas80836255** [alibaba/RedisShake#122]
1 . Can set delay in sync function ?

`2019/07/11 16:33:12 [INFO] dbSyncer[0] sync:  +forwardCommands=3      +filterCommands=0      +writeBytes=262`

2. Can set schedule for run sync command ?

thank you

**Comment by vinllen** [comment]
1. Do you mean that RedisShake should add the syncing delay time in the print log so that user can know the syncing time gap between the source and target Redis? e.g., 
`2019/07/11 16:33:12 [INFO] dbSyncer[0] sync: +forwardCommands=3 +filterCommands=0 +writeBytes=262 +delay=5ms`.
The answer is no, generally speaking, RedisShake sends commands to the target Redis once receiving commands, and the delay depends on the network.
2. I'm not very clear about this question, could you make it more clear?

**Comment by bas80836255** [comment]
sorry for reply late

In question 2. I want to move all data from source redis to target redis at 7.00 am  everyday.
what should i do?

**Comment by vinllen** [comment]
You can run a bash script like Linux `cron` to start a scheduled task at 7:00 am to do this job.

**Comment by bas80836255** [comment]
Ok Thank for answer. It very helpful.
